; This is an example file, please rename it to config.ini and fill in the values
[WEBHOOK]
id = 
token =
msg_id =

[UPDATER]
repo_owner =
repo_name =
branch =
trigger = [RELEASE]
local_repo_path =

[PRINTER]
ip =
serial =
access_code =