; This is an example file, please rename it to config.ini and fill in the neccesary values
; When you get a discord Webhook link (discord channel settings > Integrations > Webhooks > New Webhook) 
; the id is the long number in the URL and the token is the long jumble of letters and numbers after it
[WEBHOOK]
id = 
token = 
; This will be set / changed by the program, automatically
msg_id = 

[UPDATER]
; These have to stay the same to update correctly
repo_owner = LostScriptures
repo_name = UpdateFox
branch = main
; These will be changed / set by the program, automatically
local_repo_path = 
last_sha = 
next_update_check = 

; These have to be set by you 
; ip is the printer's local IP address
; serial is the printer's serial number, found under settings > Device > Printer SN
; access_code is the printer's access code, found under LAN Mode (has to be enabled) > acess code
; the printer also has to be in Developer Mode (also found under LAN Mode but only whern enabled)
[PRINTER]
ip = 
serial = 
access_code = 

